#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
#
##Hibernate auto ddl //we will use this to drop existing or create tables after creation
#spring.jpa.hibernate.ddl-auto=create
#
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#
##logging to see hibernate intended queries
#logging.level.org.hibernate.SQL=DEBUG
#
##catch errors
#spring.mvc.throw-exception-if-no-handler-found=true
#spring.web.resources.add-mappings=false
#
##cloudinary configuration
#spring.config.import = env.properties
#cloud_name=${CLOUD_NAME}
#api_key=${API_KEY}
#api_secret=${API_SECRET}